### ISSUE TITLE
Hostsman doesn't work with Github

### ISSUE THREAD

**Issue by mtxadmin** [vdbhb59/hosts#8]
Readme.md : "Users for Windows would find it easy to use with Hostman"

As far as I know, Hostsman does not work with Github-hosted hosts. See https://github.com/crazy-max/WindowsSpyBlocker/issues/103

https://github.com/mtxadmin/ublock/blob/master/docs/hosts_file_en.md

**Comment by vdbhb59** [comment]
You are talking about "Hostsman", and I mean "Hostman" application for Windows. Both are different. Moreover, I just tried it out yesterday, and I can see github raw as well as text URLs work fine with it.

Plus that issue is from long ago. Anyways, I have moved out of github URLs and you can see that in my readme as well as the resulting URLs for hosts file. So no worries anyways.
